import React from 'react';
import {
  Activity,
  ArrowLeft,
  ArrowRight,
  Award,
  BadgeCheck,
  BarChart3,
  Bell,
  BookOpen,
  Bot,
  Brain,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardCheck,
  CircleX,
  Copy,
  Euro,
  Eye,
  FileDown,
  FileText,
  FlaskConical,
  Flame,
  FolderKanban,
  Handshake,
  HelpCircle,
  Info,
  Kanban,
  LayoutDashboard,
  Layers3,
  Library,
  Lock,
  LogIn,
  LogOut,
  Medal,
  MessageSquare,
  MessageSquareWarning,
  Minus,
  Pencil,
  Play,
  Plus,
  PlusCircle,
  Radar,
  RefreshCw,
  Route,
  Save,
  Search,
  Settings,
  ShieldCheck,
  Shapes,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Target,
  ThumbsUp,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserRound,
  UserPlus,
  Users,
  Wallet,
  PhoneCall,
  X,
  Zap,
  Moon,
} from 'lucide-react';

const ICON_MAP = {
  // Mockup-native keys
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  activity: Activity,
  award: Award,
  'bar-chart-2': BarChart3,
  bell: Bell,
  brain: Brain,
  bolt: Zap,
  'book-open': BookOpen,
  bot: Bot,
  'badge-check': BadgeCheck,
  calendar: Calendar,
  'calendar-days': CalendarDays,
  check: Check,
  'check-circle': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'clipboard-check': ClipboardCheck,
  'circle-x': CircleX,
  copy: Copy,
  euro: Euro,
  eye: Eye,
  'file-down': FileDown,
  'file-text': FileText,
  flame: Flame,
  'flask-conical': FlaskConical,
  handshake: Handshake,
  info: Info,
  kanban: Kanban,
  'layout-dashboard': LayoutDashboard,
  'layers-3': Layers3,
  lock: Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  medal: Medal,
  'message-square': MessageSquare,
  'message-square-warning': MessageSquareWarning,
  minus: Minus,
  pencil: Pencil,
  play: Play,
  'phone-call': PhoneCall,
  plus: Plus,
  'plus-circle': PlusCircle,
  'refresh-cw': RefreshCw,
  route: Route,
  save: Save,
  shape: Shapes,
  settings: Settings,
  'shield-check': ShieldCheck,
  sliders: SlidersHorizontal,
  sparkles: Sparkles,
  target: Target,
  'thumbs-up': ThumbsUp,
  'trending-up': TrendingUp,
  trophy: Trophy,
  upload: Upload,
  user: User,
  'user-round': UserRound,
  'user-plus': UserPlus,
  users: Users,
  wallet: Wallet,
  x: X,
  zap: Zap,

  // Existing app keys (material-symbol aliases)
  dashboard: LayoutDashboard,
  analytics: FolderKanban,
  forum: MessageSquare,
  description: FileText,
  groups: Users,
  emoji_events: Trophy,
  query_stats: BarChart3,
  library_books: Library,
  logout: LogOut,
  notifications: Bell,
  help: HelpCircle,
  local_fire_department: Flame,
  timeline: Activity,
  radar: Radar,
  psychology: Brain,
  summarize: FileText,
  insights: BarChart3,
  military_tech: Medal,
  verified: CheckCircle2,
  category: BookOpen,
  search: Search,
  light_mode: Sun,
  dark_mode: Moon,
};

function normalize(name) {
  return String(name || '')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, '-');
}

export function Icon({ name, size = 18, color = 'currentColor', strokeWidth = 1.8, className = '', ...rest }) {
  const key = normalize(name);
  const Cmp = ICON_MAP[key] || Info;
  return <Cmp size={size} color={color} strokeWidth={strokeWidth} className={className} {...rest} />;
}
